Update build-linux.yml

diff --git a/.github/workflows/build-linux.yml b/.github/workflows/build-linux.yml
--- a/.github/workflows/build-linux.yml
+++ b/.github/workflows/build-linux.yml
@@ -10,27 +10,50 @@ on:
         required: true
         type: string
 
+defaults:
+  run:
+    # "--login" carries over env. variables from one "run" command to the next.
+    # "--norc" means "do not execute ~/.bashrc .
+    # "-eo pipefail" causes the shell to exit immediately if any simple command fails 
+    # (exits with a non-zero status). The exit status of a pipeline
+    # (a sequence of commands connected by |) is:
+    # the status of the rightmost command to exit with a non-zero status, 
+    # or zero if all commands succeed.
+    shell: bash --login --norc -eo pipefail {0}
+
 jobs:
   build:
+    # The type of runner that the job will run on
     runs-on: ubuntu-latest
     steps:
+      # Avoid \r\n line endings
+      - run: git config --global core.autocrlf input
+      
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: List the checked out LisaEm files (the top folder only)
+        run: ls -la .
+        
       - name: Install libraries that are needed to build wxWidgets
         run: |
           sudo apt-get update
           sudo apt-get install -y libtiff6 libtiff-dev build-essential libgtk-3-dev
           
-      - name: Build wxWidgets
+      - name: Build and install wxWidgets
         run: |
           ./scripts/build-wx3.2.1-gtk.sh
           
-      - name: Build LisaEm
+      - name: Build and package LisaEm
         run: |
-          build.sh clean build
+          ./build.sh clean build package
+
+      - name: List the generated files
+        run: |
+          ls -l ./bin/lisaem
+          ls -l ./pkg/LisaEm_Linux_x86_64.AppImage
           
-      - name: Package AppImage
+      - name: Rename AppImage file to include version and date
         run: |
           # Use the variables passed from the master to name the file
           FILENAME="LisaEm-${{ inputs.version_id }}-${{ inputs.today }}-Linux_x86_64.AppImage"
